att1:
	gcc -nostdlib -nostartfiles -static -Wl,-e,_start -o prog1-att codigo1-att-sintaxe.s


intel1:
	gcc -nostdlib -nostartfiles -static -Wl,-e,_start -o prog1-intel codigo1-intel-sintaxe.s


att2:
	gcc -nostdlib -nostartfiles -static -Wl,-e,_start -o prog2-att codigo2-att-sintaxe.s


intel2:
	gcc -nostdlib -nostartfiles -static -Wl,-e,_start -o prog2-intel codigo2-intel-sintaxe.s